spring:
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/news-portal-g-48"
    username: "postgres"
    password: "248842"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5000
      driver-class-name: "org.postgresql.Driver"

client:
  newsapi:
    properties:
      api-key: "40f23b5268a54562ad05a0e112b4e433"
      base-url: "https://newsapi.org"

